# Interactive Ruby
# irb

# !                              else
# !=                             elsif
# !~                             end
# <=>                            ensure
# ==                             enum_for
# ===                            eql?
# =~                             equal?
# @prompt                        eval
# ARGF                           exec
# ARGV                           exit
# ArgumentError                  exit!
# Array                          extend
# BEGIN                          fail
# BasicObject                    false
# Bignum                         fg
# Binding                        for
# CROSS_COMPILING                fork
# Class                          format
# ClosedQueueError               freeze
# Comparable                     frozen?
# Complex                        gem
# ConditionVariable              gem_original_require
# Data                           gets
# DelegateClass                  global_variables
# Delegator                      hash
# DidYouMean                     help
# Dir                            if
# END                            in
# ENV                            include
# EOFError                       initialize
# Encoding                       initialize_clone
# EncodingError                  initialize_copy
# Enumerable                     initialize_dup
# Enumerator                     inspect
# Errno                          install_alias_method
# Exception                      instance_eval
# Exception2MessageMapper        instance_exec
# FALSE                          instance_of?
# FalseClass                     instance_variable_defined?
# Fiber                          instance_variable_get
# FiberError                     instance_variable_set
# File                           instance_variables
# FileTest                       irb
# FileUtils                      irb_binding
# Fixnum                         irb_bindings
# Float                          irb_cb
# FloatDomainError               irb_change_binding
# FrozenError                    irb_change_workspace
# GC                             irb_chws
# Gem                            irb_context
# Hash                           irb_current_working_binding
# IO                             irb_current_working_workspace
# IOError                        irb_cwb
# IPAddr                         irb_cws
# IPSocket                       irb_cwws
# IRB                            irb_exit
# IndexError                     irb_exit_org
# Integer                        irb_fg
# Interrupt                      irb_help
# Kernel                         irb_jobs
# KeyError                       irb_kill
# LoadError                      irb_load
# LocalJumpError                 irb_pop_binding
# Marshal                        irb_pop_workspace
# MatchData                      irb_popb
# Math                           irb_popws
# Method                         irb_print_working_binding
# Module                         irb_print_working_workspace
# Monitor                        irb_push_binding
# MonitorMixin                   irb_push_workspace
# Mutex                          irb_pushb
# NIL                            irb_pushws
# NameError                      irb_pwb
# NilClass                       irb_pwws
# NoMemoryError                  irb_quit
# NoMethodError                  irb_require
# NotImplementedError            irb_source
# Numeric                        irb_workspaces
# Object                         is_a?
# ObjectSpace                    iterator?
# Proc                           itself
# Process                        jobs
# Queue                          kill
# RUBYGEMS_ACTIVATION_MONITOR    kind_of?
# RUBY_COPYRIGHT                 lambda
# RUBY_DESCRIPTION               load
# RUBY_ENGINE                    local_variables
# RUBY_ENGINE_VERSION            loop
# RUBY_PATCHLEVEL                method
# RUBY_PLATFORM                  method_missing
# RUBY_RELEASE_DATE              methods
# RUBY_REVISION                  module
# RUBY_VERSION                   next
# Random                         nil
# Range                          nil?
# RangeError                     not
# Rational                       num
# RbConfig                       object_id
# Readline                       open
# Regexp                         or
# RegexpError                    p
# RubyLex                        popb
# RubyToken                      popws
# RubyVM                         pp
# RuntimeError                   print
# STDERR                         printf
# STDIN                          private
# STDOUT                         private_methods
# ScriptError                    proc
# SecurityError                  protected_methods
# Set                            public
# Signal                         public_method
# SignalException                public_methods
# SimpleDelegator                public_send
# SizedQueue                     pushb
# SortedSet                      pushws
# StandardError                  putc
# StopIteration                  puts
# String                         pwws
# StringIO                       quit
# Struct                         raise
# Symbol                         rand
# SyntaxError                    readline
# SystemCallError                readlines
# SystemExit                     redo
# SystemStackError               remove_instance_variable
# TOPLEVEL_BINDING               require
# TRUE                           require_relative
# TSort                          rescue
# Thread                         respond_to?
# ThreadError                    respond_to_missing?
# ThreadGroup                    retry
# Time                           return
# TracePoint                     sayhi
# TrueClass                      select
# TypeError                      self
# URI                            send
# UnboundMethod                  set_trace_func
# UncaughtThrowError             singleton_class
# UnicodeNormalize               singleton_method
# Warning                        singleton_method_added
# ZeroDivisionError              singleton_method_removed
# _                              singleton_method_undefined
# __callee__                     singleton_methods
# __dir__                        sleep
# __id__                         source
# __method__                     spawn
# __send__                       sprintf
# `                              srand
# abort                          super
# alias                          syscall
# and                            system
# at_exit                        taint
# autoload                       tainted?
# autoload?                      tap
# begin                          test
# binding                        then
# bindings                       throw
# block_given?                   to_enum
# break                          to_s
# caller                         trace_var
# caller_locations               trap
# case                           true
# catch                          trust
# cb                             undef
# chws                           unless
# class                          untaint
# clone                          until
# conf                           untrace_var
# context                        untrust
# cws                            untrusted?
# cwws                           using
# def                            warn
# define_method                  when
# define_singleton_method        while
# defined                        workspaces
# display                        yield
# do                             yield_self
# dup
